name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags (e.g., v1.0.0)

permissions:  # Global permissions
  contents: write  # Needed to create a release
  packages: write  # Needed if you're also publishing packages
  issues: read     # Optional, only if your workflow interacts with issues
  pull-requests: read # Optional, only if your workflow interacts with pull requests


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify the version of the .NET SDK you want to use

    - name: Restore dependencies
      run: dotnet restore Text_Editor.sln

    - name: Build
      run: dotnet build Text_Editor.sln --configuration Release

    - name: Publish
      run: dotnet publish Text_Editor/Text_Editor.csproj --configuration Release --output D:\a\lil_Text\lil_Text\release

    - name: Working directory
      run: cd release

    - name: listing files
      run: ls

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}  # Uses the tag_name that triggered the workflow
        files: D:\a\lil_Text\lil_Text\release/*

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
